### ISSUE TITLE
Add TAGE-SC-L to ChampSim

### ISSUE THREAD

**Issue by AminAvan** [craymichael/CBP-16-Simulation#1]
Hi
I want to add the "TAGE-SC-L" on [ChampSim](https://github.com/ChampSim/ChampSim#clone-champsim-repository), the ChampSim already have <<bimodal, gshare, perceptron, hashed-perceptron>>, I add the TAGE on by myself, but I add the TAGE that proposed in 2006.
As you work on CBP-16, would you please guide me to add TAGE-SC-L on the ChampSim?
Bests

**Comment by craymichael** [comment]
Hi, I am more familiar with the additional code added in this repository rather than the CBP-16 simulation code itself. It looks like you will want to follow the examples at ChampSim - https://github.com/ChampSim/ChampSim/tree/master/branch. The TAGE-SC-L files will need to be modified to fit the design of ChampSim:

```cpp
void O3_CPU::initialize_branch_predictor()
uint8_t O3_CPU::predict_branch(uint64_t ip)
void O3_CPU::last_branch_result(uint64_t ip, uint8_t taken)
```

After pulling in CBP-16 with the [setup_cbp16.sh](https://github.com/craymichael/CBP-16-Simulation/blob/master/scripts/setup_cbp16.sh) script you'll need to take a look at the files in the CBP-16 `submissions/AndreSeznec/` directory (predictor.cc  and predictor.h). I do not have the bandwidth to help translate the two, but hopefully this is enough to start work.
